[project]
name = "llm-chunker"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.1.0",
    "nltk>=3.6",
    "openai>=1.0.0",
    "python-dotenv>=1.2.1",
]
